version: "3.9"

services:

  index:
    build:
      context: .
      target: website-index
    ports:
      - 443:3000
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./certs
        target: /home/website/certs
    deploy:
      resources:
        limits:
          memory: 100M

  apps:
    build:
      context: .
      target: website-apps
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./certs
        target: /home/website/certs
    deploy:
      resources:
        limits:
          memory: 100M
