name: CI build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          cache: maven

      - name: Run Maven build
        run: mvn clean install -P prod -ntp

      - name: Report test results
        uses: dorny/test-reporter@v2
        with:
          name: JUnit test results
          path: '**/TEST-*.xml'
          reporter: java-junit

  build-website-build-jre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
          build-args: |
            'JDK_VERSION=24'
          context: ./build
          target: website-build-jre
          push: false

  build-website-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./build
          target: website-run
          push: false
