# Build images with docker-compose.

name: CI

# Controls when the workflow will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out code.
      - uses: actions/checkout@v2

      - name: Log in to docker registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Run docker-compose build
        run: |
          touch .env
          docker-compose build
          docker tag website_index ghcr.io/tjh90/website_index:latest
          docker push ghcr.io/tjh90/website_index:latest
          docker tag website_eightball ghcr.io/tjh90/website_eightball:latest
          docker push ghcr.io/tjh90/website_eightball:latest
